[alias]
esp32 =   "run --features   esp32 --target xtensa-esp32-none-elf        --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
esp32s2 = "run --features esp32s2 --target xtensa-esp32s2-none-elf      --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
esp32s3 = "run --features esp32s3 --target xtensa-esp32s3-none-elf      --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
esp32c2 = "run --features esp32c2 --target riscv32imc-unknown-none-elf  --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
esp32c3 = "run --features esp32c3 --target riscv32imc-unknown-none-elf  --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
esp32c6 = "run --features esp32c6 --target riscv32imac-unknown-none-elf --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
esp32h2 = "run --features esp32h2 --target riscv32imac-unknown-none-elf --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"

besp32 =   "build --features   esp32 --target xtensa-esp32-none-elf        --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
besp32s2 = "build --features esp32s2 --target xtensa-esp32s2-none-elf      --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
besp32s3 = "build --features esp32s3 --target xtensa-esp32s3-none-elf      --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
besp32c2 = "build --features esp32c2 --target riscv32imc-unknown-none-elf  --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
besp32c3 = "build --features esp32c3 --target riscv32imc-unknown-none-elf  --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
besp32c6 = "build --features esp32c6 --target riscv32imac-unknown-none-elf --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"
besp32h2 = "build --features esp32h2 --target riscv32imac-unknown-none-elf --features esp-hal/default,esp-hal/embassy-time-timg0,esp-hal/embassy-executor-thread"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
    "-C", "force-frame-pointers",
]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
    "-C", "force-frame-pointers",
]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
]

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-Trom_functions.x",
    "-C", "force-frame-pointers",
]

[unstable]
build-std = [ "core" ]
